kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
      app: nginx-service
spec:
  selector:
    app: nginx-replacement
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
  type: LoadBalancer